### ISSUE TITLE
Listener not created with only defaultBackend defined

### ISSUE THREAD

**Issue by a-chaudhari** [oracle/oci-native-ingress-controller#132]
Not sure if this is intentional or not, but if an ingress only has a default service, no listener is created.  

This prevents any requests from reaching the service.  Manually creating a listener resolves the issue.

``` yaml
apiVersion: "ingress.oraclecloud.com/v1beta1"
kind: IngressClassParameters
metadata:
  name: root-icp
  namespace: rtc
spec:
  compartmentId: "ocid1.compartment...."
  subnetId: "ocid1.subnet...."
  loadBalancerName: "root-rtc-lb"
  isPrivate: false
  maxBandwidthMbps: 400
  minBandwidthMbps: 100
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: root-ic
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  controller: oci.oraclecloud.com/native-ingress-controller
  parameters:
    scope: Namespace
    namespace: rtc
    apiGroup: ingress.oraclecloud.com
    kind: ingressclassparameters
    name: root-icp
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: root-ingress
  annotations:
    oci-native-ingress.oraclecloud.com/healthcheck-protocol: "HTTP"
    oci-native-ingress.oraclecloud.com/healthcheck-port: "8080"
    oci-native-ingress.oraclecloud.com/healthcheck-path: "/health"
    oci-native-ingress.oraclecloud.com/healthcheck-return-code: "200"
    oci-native-ingress.oraclecloud.com/healthcheck-response-regex: ".*"
    oci-native-ingress.oraclecloud.com/healthcheck-force-plaintext: "true"
spec:
  ingressClassName: root-ic
  defaultBackend:
    service:
      name: MyService
      port:
        name: http
```
