### ISSUE TITLE
Feat: Helthcheck needs to be the same to all Backends

### ISSUE THREAD

**Issue by tonybolzan** [oracle/oci-native-ingress-controller#22]
Today, it is not possible to have different healthchecks to BackendSets.
Example:
a.example.org/status
b.example.org/healthz

This force to have TCP healthcheck and a alert on Smart Healthcheck are permanently

**Comment by Inbaraj-S** [comment]
Thank you @tonybolzan  for reaching out.
Currentyl we support both TCP and HTTP healthcheck at the ingress level which applies to all the rules within.
Could you please elaborate your use case further.

**Comment by tonybolzan** [comment]
I can't have more then 1 service with different Health Check endpoint, because the Health Check are done in the annotations of ingress for all the services.

Example:
Health Check for service APP, maybe a Nginx.
`http://app-svc/healthz`
Health Check for service Assets, maybe a MinIO
`http://assets-svc/minio/health/live`

```yml
spec:
  rules:
    - host: example.com
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: app-svc
                port:
                  number: 80

          - pathType: Prefix
            path: /minio/
            backend:
              service:
                name: assets-svc
                port:
                  number: 9000
```

 In the OCI LB the Health Check are done at de BackendSet Level not at the Listener.
