### ISSUE TITLE
Unable to create ingress with routing requests based on host.

### ISSUE THREAD

**Issue by pr07pr07** [oracle/oci-native-ingress-controller#48]
We are  unable to create a ingress with routing requests based on host. Does OCI native ingress controller support this feature?
But as per below oracle it1s support:
https://docs.oracle.com/en-us/iaas/Content/ContEng/Tasks/contengsettingupnativeingresscontroller.htm

`Error from server (BadRequest): error when replacing "ingressResource.yaml": Ingress in version "v1" cannot be handled as a Ingress: strict decoding error: unknown field "spec.rules[0].http.paths[0].backend.serviceName", unknown field "spec.rules[0].http.paths[0].backend.servicePort", unknown field "spec.rules[0].http.paths[1].backend.serviceName", unknown field "spec.rules[0].http.paths[1].backend.servicePort"`

```shell
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  name: ingress 
  namespace: default
spec:
  ingressClassName: ingress-class
  rules:
    - host: "<hostname>"
      http:
        paths:
          - path: /service
            backend:
              serviceName: service
              servicePort: 80
``` 
              

Thank you in advance

**Comment by Inbaraj-S** [comment]
The structure of your ingress is incorrect, 
- You have to follow ingress standard: https://kubernetes.io/docs/reference/kubernetes-api/service-resources/ingress-v1/#IngressSpec

please find the fixed one:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  name: ingress
  namespace: default
spec:
  ingressClassName: ingress-class
  rules:
    - host: "<hostname>"
      http:
        paths:
          - path: "/service"
            backend:
              service:
                name: service
                port:
                  number: 80
            pathType: Prefix
```
