### ISSUE TITLE
Bad Gateway adding a certificate in a OCI Native Ingress Controller

### ISSUE THREAD

**Issue by naguaramaster** [oracle/oci-native-ingress-controller#59]
Good afternoon.

I am adding a certificate to the Ingress Resource in the Annotations section as indicated in the documentation.

```
kind: Ingress
metadata:
  name: <i-name>
  annotations:
    oci-native-ingress.oraclecloud.com/certificate-ocid: <certificate-ocid>
spec:
...
```

After adding it and trying to test with the created dns it gives a "Bad Gateway" error. When the certificate is removed the Load Balancer routes to the pods without problems. Ingress used:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: psu-service-ing
  namespace: ns-apps-dev
  annotations:
    oci-native-ingress.oraclecloud.com/certificate-ocid: "don't show the certificate-ocid"
spec:
  ingressClassName: native-ic-ingress-class
  rules:
  - host: "testing.testing.cl"
    http:
      paths:
      - pathType: Prefix
        path: "/psu"
        backend:
          service:
            name: psu-service-svc
            port:
              number: 443
```

What could be missing?
