### ISSUE TITLE
Ingress port showing incorrect port

### ISSUE THREAD

**Issue by matthewmcdaniel** [oracle/oci-native-ingress-controller#77]
When creating an `Ingress` resource with the following annotations

```
 oci-native-ingress.oraclecloud.com/backend-tls-enabled: "false"
 oci-native-ingress.oraclecloud.com/https-listener-port: "443"
```

With the following rules

```
tls:
  - hosts:
    - my.example.com
    secretName: tls-secret
  rules:
    - host: "my.example.com"
      http:
        paths:
          - pathType: Exact
            path: "/testecho1"
            backend:
              service:
                name: testechoone
                port:
                  number: 8081
          - pathType: Exact
            path: "/testecho2"
            backend:
              service:
                name: testechotwo
                port:
                  number: 8080
```

`kubectl get ingress` returns 

```
NAMESPACE   NAME                CLASS             HOSTS            ADDRESS           PORTS     AGE
default     ingress-readiness   ingress-class-1   my.example.com   <redacted>   80, 443   4d1h
```

I would expect the ingress port to only show 443 since I only have 1 listener which is listening on port 443. Is this intended?
