### ISSUE TITLE
IngressClass cant find IngressClassPArameters

### ISSUE THREAD

**Issue by hajime-matsumoto** [oracle/oci-native-ingress-controller#79]
ingress-controller said:  ingressclass.go:476] Error syncing ingress class avap-public-web-ingress-class: unable to fetch IngressClassParameters ic-params: IngressClassParameters.ingress.oraclecloud.com "ic-params" not found

my manifest is below.

```
---
apiVersion: "ingress.oraclecloud.com/v1beta1"
kind: IngressClassParameters
metadata:
  name: ic-params
spec:
  compartmentId: "ocid1.compartment.oc1..aaaaaaaa..."
  subnetId: "ocid1.subnet.oc1.ap-tokyo-1.aaaaaaaaa..."
  loadBalancerName: "avap-public-web-lb"
  isPrivate: false
  maxBandwidthMbps: 10
  minBandwidthMbps: 10
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: avap-public-web-ingress-class
  annotations:
    ingressclass.kubernetes.io/is-default-class: "false"
spec:
  controller: oci.oraclecloud.com/native-ingress-controller
  parameters:
    apiGroup: ingress.oraclecloud.com
    kind: ingressclassparameters
    name: ic-params

```

i can't find out waht I am missed.

**Comment by nirpai** [comment]
Can you set the namespace parameter accordingly in IngressClass and try?
```
spec:
  controller: oci.oraclecloud.com/native-ingress-controller
  parameters:
    apiGroup: ingress.oraclecloud.com
    kind: ingressclassparameters
    name: ic-params
    namespace: <namespace of cr ic-params>
```
