### ISSUE TITLE
Create a Private Load Balancer When Using OCI Native Ingress Controller

### ISSUE THREAD

**Issue by PrathapDasari** [oracle/oci-native-ingress-controller#94]
Hi,

Can we assign a Private IP Address instead of public IP address  to LB When Using OCI Native Ingress Controller?

Using OCI Native Ingress Controller. Additionally, Is It Possible to Create Two Ingress Controllers with Both Private and Public Load Balancers on the Same OKE Cluster?"

Regards,
Prathap

**Comment by piyush-tiwari** [comment]
Hi @PrathapDasari,
1. Yes, you can configure the load balancer to be private by configuring the `isPrivate` field of the corresponding `IngressClassParameters` resource to `true`. Example:
```
apiVersion: "ingress.oraclecloud.com/v1beta1"
kind: IngressClassParameters
metadata:
  name: ingressparms
  namespace: test
spec:
  compartmentId: "ocid1.compartment.oc1..___"
  subnetId: "ocid1.subnet.oc1.iad.___"
  loadBalancerName: "native-ic-lb"
  isPrivate: true
  maxBandwidthMbps: 400
  minBandwidthMbps: 100
```

2. Yes, you can have a private and a public load balancer from the same OKE cluster. Note that load balancers are mapped 1:1 with `IngressClass` resources. What you will need to do is have two separate `IngressClassParameter` resources, each configured with an appropriate `isPrivate` field, and then use these in the `parameters` field of two different `IngressClass` resources.
