### ISSUE TITLE
Issue with creating HTTP listener without SSL in ingress with certificate-ocid

### ISSUE THREAD

**Issue by iolesyk** [oracle/oci-native-ingress-controller#95]
Hi,
When I use SSL certificate from OCI certificate manager in my ingress then I can't create http listener without SSL, all listeners creating with SSL only, and I can't find a way how to create one HTTPS listener and one HTTP listener using certificate from OCI certificate manager.

My example:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-test
  annotations:
    kubernetes.io/ingress.class: "ingress-class"
    oci-native-ingress.oraclecloud.com/certificate-ocid: "ocid1.certificate...."
    oci-native-ingress.oraclecloud.com/protocol: "HTTP2"
    oci-native-ingress.oraclecloud.com/backend-tls-enabled: "false"
    oci-native-ingress.oraclecloud.com/healthcheck-protocol: http
    oci-native-ingress.oraclecloud.com/healthcheck-port: "80"
    oci-native-ingress.oraclecloud.com/healthcheck-path: "/"
   
spec:
  ingressClassName: ingress-class
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: https-service
                port:
                  number: 443
    - http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: http-service
                  port:
                    number: 80
```
Any information will help, thank you.
